times = ('palmeiras','internacional', 'fluminense', 'corintinhas', 'flamengo ', 'athlético-PR', 'athlético-MG', 'fortaleza', 'são paulo', 'américa-MG', 'botafogo', 'santos', 'goiás', 'bragantino', 'coritiba', 'cuiabá', 'ceará', 'atlético-GO', 'Avaí', 'juventude')
print('-=' * 55)
print(f'Lista de times do brasileirão: {times}')
print('-=' * 55)
print(f'Os 5 primeiros são {times[0:5]}')
print('-=' * 55)
print(f'os 4 últimos colocados são {times[-4:]}')
print('-=' * 55)
print(f'Times em ordem alfabética: {sorted(times)}')
print('-=' * 55)
print(f'O corintinhas está em {times.index("corintinhas")+1}ª posição')
print('-=' * 55)
